In [1]:
import numpy as np
import pandas as pd
df=pd.read_excel("/content/campaign_data_knovista_project (3).xlsx")
df

,Campaign,Total Leads,Sales,Conversion Rate (%),Cost per Lead,Total Cost
0,PY | KL | Fee included 2,60,6,10.00,68.62,4117.20
1,DA | KL | No monitory benefit 13,173,3,1.73,47.97,8298.81
2,PY | KL | Hiring,65,0,0.00,55.63,3615.95
3,PY | KL | Fee included,231,11,4.76,41.15,9505.65
4,DA | KL | Hiring,294,11,3.74,28.06,8249.64
...,...,...,...,...,...,...
5995,BA-Hiring 1,137,9,6.57,20.12,2756.44
5996,PY | KL | Hiring | Sep 18,165,6,3.64,22.49,3710.85
5997,PY | KL | Hiring | Sep 9,218,16,7.34,39.44,8597.92
5998,PY | KL | Hiring | Sep 9,198,13,6.57,35.23,6975.54


Check shape,size,null values and data types

In [2]:
print(df.shape)
print(df.size)
print(df.isna().sum())
print(df.dtypes)

(6000, 6)
36000
Campaign               0
Total Leads            0
Sales                  0
Conversion Rate (%)    0
Cost per Lead          0
Total Cost             0
dtype: int64
Campaign                object
Total Leads              int64
Sales                    int64
Conversion Rate (%)    float64
Cost per Lead          float64
Total Cost             float64
dtype: object


Input

In [3]:
x=df.drop(['Campaign','Sales'],axis=1).values
x

array([[6.00000e+01, 1.00000e+01, 6.86200e+01, 4.11720e+03],
       [1.73000e+02, 1.73000e+00, 4.79700e+01, 8.29881e+03],
       [6.50000e+01, 0.00000e+00, 5.56300e+01, 3.61595e+03],
       ...,
       [2.18000e+02, 7.34000e+00, 3.94400e+01, 8.59792e+03],
       [1.98000e+02, 6.57000e+00, 3.52300e+01, 6.97554e+03],
       [2.60000e+02, 1.92000e+00, 2.57000e+01, 6.68200e+03]])

Output

In [4]:
y=df['Sales'].values
y

array([ 6,  3,  0, ..., 16, 13,  5])

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
x_train

array([[2.840000e+02, 1.760000e+00, 5.624000e+01, 1.597216e+04],
       [2.330000e+02, 3.860000e+00, 3.562000e+01, 8.299460e+03],
       [2.950000e+02, 4.070000e+00, 4.640000e+01, 1.368800e+04],
       ...,
       [2.040000e+02, 6.860000e+00, 1.894000e+01, 3.863760e+03],
       [2.950000e+02, 6.800000e-01, 7.910000e+00, 2.333450e+03],
       [9.800000e+01, 3.060000e+00, 6.580000e+01, 6.448400e+03]])

In [6]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
rf=RandomForestRegressor()
p={'n_estimators':[50,100,150],'max_depth':[3,5,7,9,11]}
gd=GridSearchCV(rf,p,cv=10,scoring='r2')
gd.fit(x_train,y_train)
print(gd.best_params_)

{'max_depth': 11, 'n_estimators': 150}


In [7]:
rf1=RandomForestRegressor(n_estimators=150,max_depth=11)
rf1.fit(x_train,y_train)
y_pred=rf1.predict(x_test)
print(y_pred)


[ 2.         10.06222222 12.96666667 ...  1.         21.64029813
 10.97971014]


In [8]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score
print(mean_absolute_percentage_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

0.005923464691226788
0.999716892428754
